[pytest]
python_classes = Test*
python_files = test_*.py
python_functions = test_*

# Ignore SQLAlchemy model classes that start with "Test"
filterwarnings =
    ignore::pytest.PytestCollectionWarning
